version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.18.2"
      TYPE: "FORGE"
      FORGE_VERSION: "40.2.0"
    volumes:
      - "./data:/data"
      - "./mods:/mods"
    restart: unless-stopped
