version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.18.2"
      TYPE: "FORGE"
      FORGE_VERSION: "40.2.0"
      nogui: "true"
    volumes:
      - "./mods:/mods"  # Mantén esta línea si usas mods
    restart: unless-stopped
